name: docker-course-app

services:
  client-react-vite:
    image: client-react-vite
    build:
      context: ../client-react
      dockerfile: ../dockerfiles/client-react/Dockerfile.4
    init: true
    networks:
      - frontend
    volumes:
      - ${PWD}/client-react/vite.config.js:/usr/src/app/vite.config.js
    ports:
      - "5173:5173"

  client-react-nginx:
    image: client-react-nginx
    build:
      context: ../client-react
      dockerfile: ../dockerfiles/client-react/Dockerfile.6
    init: true
    networks:
      - frontend
    ports:
      - "80:8080"
    restart: unless-stopped

  api-node:
    image: api-node
    build:
      context: ../api-node
      dockerfile: ../dockerfiles/api-node/Dockerfile.8
    init: true
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:foobarbaz@db:5432/postgres
    networks:
      - frontend
      - backend
    ports:
      - "3000:3000"
    restart: unless-stopped

  api-golang:
    image: api-golang
    build:
      context: ../api-golang
      dockerfile: ../dockerfiles/api-golang/Dockerfile.8
    init: true
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:foobarbaz@db:5432/postgres
    networks:
      - frontend
      - backend
    ports:
      - "8080:8080"
    restart: unless-stopped

  db:
    image: postgres:18.3-alpine3.23
    environment:
      - POSTGRES_PASSWORD=foobarbaz
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped

volumes:
  pgdata:

networks:
  frontend:
  backend: