services:
  api-node:
    command: 
      - "npm"
      - "run"
      - "debug-docker"
    ports:
      - "3000:3000"
      - "9229:9229"

  api-golang:
    command: 
      - "dlv"
      - "debug"
      - "--headless"
      - "--api-version=2"
      - "--log"
      - "--log-output=debugger,dap,rpc"
      - "--listen=:2345"
      - "--accept-multiclient"
      - "--continue"
    ports:
      - "8080:8080"
      - "2345:2345"