name: docker-course
services:
  client-vite:
    container_name: client-vite
    build:
      context: ./client
      dockerfile: ../dockerfiles/client/Dockerfile.0
    init: true
    networks:
      - frontend
    volumes:
      - type: bind
        source: ./client
        target: /usr/src/app
      - type: volume
        target: /usr/src/app/node_modules
      - type: bind
        source: ./running-containers/vite.config.js
        target: /usr/src/app/vite.config.js
    ports:
      - 5173:5173
    restart: unless-stopped
    image: client-vite
  client-nginx:
    container_name: client-nginx
    build:
      context: ./client
      dockerfile: ../dockerfiles/client/Dockerfile.1
    init: true
    networks:
      - frontend
    ports:
      - 80:8080
    restart: unless-stopped
    image: client-nginx
  api-node:
    container_name: api-node
    build:
      context: ./api-node
      dockerfile: ../dockerfiles/api-node/Dockerfile.2
      target: dev
    init: true
    depends_on:
      - db
    networks:
      - frontend
      - backend
    volumes:
      - type: bind
        source: ./api-node
        target: /usr/src/app
      - type: volume
        target: /usr/src/app/node_modules
    environment:
      - DATABASE_URL=postgres://postgres:foobarbaz@db:5432/postgres
    ports:
      - 3000:3000
    restart: unless-stopped
    image: api-node
  api-golang:
    container_name: api-golang
    build:
      context: ./api-golang
      dockerfile: ../dockerfiles/api-golang/Dockerfile.1
      target: dev
    init: true
    depends_on:
      - db
    networks:
      - frontend
      - backend
    volumes:
      - type: bind
        source: ./api-golang
        target: /app
    environment:
      - DATABASE_URL=postgres://postgres:foobarbaz@db:5432/postgres
    ports:
      - 8080:8080
    restart: unless-stopped
    image: api-golang
  db:
    container_name: db
    networks:
      - backend
    environment:
      - POSTGRES_PASSWORD=foobarbaz
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - 5432:5432
    restart: unless-stopped
    image: postgres:18.6-alpine
volumes:
  pgdata:
networks:
  frontend:
  backend:
