FROM node:25-bookworm-slim

WORKDIR /usr/src/app

ENV NODE_ENV=production

COPY package.json yarn.lock ./

RUN --mount=type=cache,target=/usr/src/app/.yarn_cache \
    yarn config set cache-folder /usr/src/app/.yarn_cache && \
    yarn --frozen-lockfile --production

USER node

COPY --chown=node:node ./src .

EXPOSE 3000

CMD [ "node", "index.js" ]