FROM golang:1.25.8-bookworm AS build

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 \
    GOOS=linux \ 
    go build -a \
    -ldflags='-w -s' \
    -o api-golang

FROM scratch

ENV GIN_MODE=release

COPY --from=build /app/api-golang api-golang

EXPOSE 8080

CMD [ "/api-golang" ]