FROM golang:1.25.8-bookworm AS build

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 \
    GOOS=linux \ 
    go build -a \
    -ldflags='-w -s' \
    -o api-golang .

FROM scratch

COPY --from=build /app/api-golang api-golang

CMD [ "api-golang" ]