FROM golang:1.25.8-bookworm AS build

WORKDIR /app

RUN useradd -u 1001 nonroot

COPY go.mod go.sum ./

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go mod download

COPY . .

RUN CGO_ENABLED=0 \
    GOOS=linux \ 
    go build -a \
    -ldflags='-w -s' \
    -o healthcheck \
    ./healthcheck/healthcheck.go

RUN CGO_ENABLED=0 \
    GOOS=linux \ 
    go build -a \
    -ldflags='-w -s' \
    -o api-golang .

FROM scratch

ENV GIN_MODE=release

WORKDIR /app

COPY --from=build /etc/passwd /etc/passwd

COPY --from=build /app/healthcheck/healthcheck .

COPY --from=build /app/api-golang .

USER nonroot

EXPOSE 8080

CMD [ "./api-golang" ]