FROM golang:1.25.8-bookworm AS build

WORKDIR /app

COPY go.mod go.sum ./

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go mod download

COPY . .

RUN CGO_ENABLED=0 \
    GOOS=linux \ 
    go build -a \
    -ldflags='-w -s' \
    -o api-golang .

FROM scratch

ENV GIN_MODE=release

COPY --from=build /app/api-golang api-golang

EXPOSE 8080

CMD [ "/api-golang" ]